### ISSUE TITLE
dependencies from repo.spring.io c

### ISSUE THREAD

**Issue by iman-badr** [Open-MBEE/exec-mms#122]
I have experienced the issue reported in the following link. 
https://spring.io/blog/2020/10/29/notice-of-permissions-changes-to-repo-spring-io-fall-and-winter-2020
Having changed release to snapshot, I got rid of some errors but I am still stuck´at a related error when running ./gradlew bootRun --scan

Execution failed for task ':elastic:compileJava'.
> Could not resolve all files for configuration ':elastic:compileClasspath'.
   > Could not download commons-logging-1.1.3.jar (commons-logging:commons-logging:1.1.3)
      > Could not get resource 'https://repo.spring.io/plugins-snapshot/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar'.
         > Could not GET 'https://repo.spring.io/plugins-snapshot/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar'. Received status code 401 from server: Unauthorized

**Comment by dlamoris** [comment]
the fix should be on develop branch now

**Comment by iman-badr** [comment]
Thank you for the promt reply
the bootBuild task is not recognized any more at the modified branch and calling gradle for this task results in the following exception:
$ ./gradlew bootBuild --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Task 'bootBuild' not found in root project 'sdvc'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.execution.TaskSelectionException: Task 'bootBuild' not found in root project 'sdvc'.
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:117)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:82)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:46)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:58)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:66)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:45)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:58)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:66)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:58)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.run(DefaultBuildConfigurationActionExecuter.java:44)
        at org.gradle.internal.Factories$1.create(Factories.java:26)
